apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uwbu6l887-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f28b3c9625.ps9p.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:83c9cae9f34755ad110f872844fae72684d0a074@sha256:3306bc4c997a94c6a86366a25ce8b7ec00d55591bbd104c3cf5c7e4872979d1e
          name: container-image
